version: '3'

services:
  # snakemake tool has all services
  # * REST
  # * dash (plotly)
  # * mongo

  snakemake_tool:
    build:
      dockerfile: Dockerfile
      context: .
    image: snakemake_tool:0.0.1
    ports:
      - "18000:80"  # FastApi
      - "14500:4050" # Dash
    # networks:
    #   - app-network
    # depends_on:
    #   - mongo

  rest_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: rest_app:0.0.1
    ports:
      - "4500:4050"
    # networks:
    #   - app-network
    # depends_on:
    #   - mongo


  dash_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: rest_app:0.0.1
    ports:
      - "4500:4050"
    # networks:
    #   - app-network
    # depends_on:
    #   - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
